name = "Interception"
uuid = "5df85826-c895-11e9-0b7e-6147820a07a9"
authors = ["Jon Alm Eriksen <jon.alm.eriksen@protonmail.com>"]
version = "0.1.0"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
